#!/usr/bin/env php
<?php

declare(strict_types=1);

use Dotenv\Dotenv;
use Yiisoft\Di\Container;
use Yiisoft\Di\ContainerConfig;
use Yiisoft\Yii\Console\Application;
use Yiisoft\Yii\Console\ExitCode;
use Yiisoft\Yii\Console\Output\ConsoleBufferedOutput;

require_once __DIR__ . '/vendor/autoload.php';

Dotenv::createMutable(
    __DIR__ . (getenv('APP_ENV') === 'test' ? '/tests' : '/')
)->load();

$container = new Container(
    ContainerConfig::create()->withDefinitions(
        require __DIR__ . '/config/definitions.php'
    )
);

$application = $container->get(Application::class);

$exitCode = ExitCode::UNSPECIFIED_ERROR;

try {
    $application->start();
    $exitCode = $application->run(null, new ConsoleBufferedOutput());
} catch (Error $error) {
    $application->renderThrowable($error, new ConsoleBufferedOutput());
} finally {
    $application->shutdown($exitCode);
    exit($exitCode);
}
